### PR TITLE
Corrected "Independent within March 14" to "Independent within 14 March".

### PR DESCRIPTION
**Pull request by chaficnajjar**

### CODE REVIEW

**Comment by kamicut** [comment]
For #4 and #5, fixing the csv will not affect the API. The API pulls directly from a Google Spreadsheet. This is of course, not sustainable, and we are looking for better options.

**Comment by chaficnajjar** [comment]
Do you plan on making it possible for individuals who do not know how to use Github to propose changes? If not, how about directly editing the CSV file through Github and have the API read from the file?

You also previously mentioned the work in progress http://flatsheet.io/. I think that's the best option.

**Comment by aboustayyef** [comment]
Why don't we just build a CRUD to edit and add to this data? Shouldn't be
too hard.

On Wednesday, August 26, 2015, Chafic notifications@github.com wrote:

> Do you plan on making it possible for individuals who do not know how to
> use Github to propose changes? If not, how about directly editing the CSV
> file through Github and have the API read from the file?
> 
> You also previously mentioned the work in progress http://flatsheet.io/.
> I think that's the best option.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openleb/nouwweb/pull/5#issuecomment-134806221.

## 

Mustapha Hamoui,
Executive Director, H.R, Admin
Tarzan Ent. Ltd.

Fax: +233 21 664 625
mobile: +233244331123

**Comment by chaficnajjar** [comment]
@aboustayyef could you elaborate?

Also @kamicut, exactly who should have the ability to add, edit or delete data?

**Pull request closed without merging**
